spring:
  application:
    name: template
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fault_diagnosis?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
  # redis配置
  data:
    redis:
      host: 10.211.55.8
      port: 6379
      password: xzl.995
  # mongodb配置
    mongodb:
      host: localhost
      database: articledb
      port: 27017

  # rabbitmq配置
  rabbitmq:
    host: 10.211.55.7
    username: zl-mq
    password: xzl.995
    port: 5672
    connection-timeout: 1s # 设置MQ的连接超时时间
    template:
      retry:
        enabled: true # 开启超时重试机制
        initial-interval: 1000ms # 失败后的初始等待时间
        multiplier: 1 # 失败后下次的等待时长倍数，下次等待时长 = initial-interval * multiplier
        max-attempts: 3 # 最大重试次数
    publisher-confirm-type: correlated # 开启publisher confirm机制，并设置confirm类型
    publisher-returns: true # 开启publisher return机制
    # 开启消费者的确认机制
    listener:
      simple:
        acknowledge-mode: auto #自动确认
        retry:
          enabled: true # 开启消费者失败重试
          initial-interval: 1000ms # 初识的失败等待时长为1秒
          multiplier: 1 # 失败的等待时长倍数，下次等待时长 = multiplier * last-interval
          max-attempts: 3 # 最大重试次数
          stateless: true # true无状态；false有状态。如果业务中包含事务，这里改为false


  # elasticsearch配置
  elasticsearch:
    uris: http://localhost:9200
# mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #??
    map-underscore-to-camel-case: true #??????

logging:
  level:
    com.zl.template: debug
